:github-readme: ../../README.adoc

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{git-repository}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please git-link:self[edit it on GitHub].

include::{github-readme}[tags=description]

=== Linter examples

These projects are using the jxlint framework and demonstrate how static analysis tools can be written.

==== txtlinter

git-link:txtlinter/[txtlinter (GitHub)] is a linter example that performs some checks on `*.txt` files:

* Lines should not be longer than 80 characters, read-more at: git-link:/txtlinter-core/src/main/resources/doc/rules/LinesAreNotLongerThan80CharsRule.md[LinesAreNotLongerThan80CharsRule]
* Multiple empty new lines at the end of the document are not allowed, read-more at: git-link:/txtlinter-core/src/main/resources/doc/rules/NoMultipleNewLinesAtTheEndRule.md[NoMultipleNewLinesAtTheEndRule]

From a code point of view:

* Separation of the modules (`txtlinter-core`, `txtlinter-cli`, `txtlinter-maven-plugin`).
* It is not using a custom category, but `com.selesse.jxlint.model.rules.Category`.

==== charchecker

git-link:txtlinter/[charchecker (GitHub)] is a linter example that ensure that the lines of the text files do not contains certain characters.
This is a technical project.
The intention is not to have rules that could be real use cases.

From a code point of view:

* All in one modules (same jar used a maven plugin and for the command line usage)
* Custom category: `fr.jmini.charchecker.CharCheckerCategory` providing 2 values:
** `Letter`
** `Number`

The rules are:

LowercaseRule::
include::../../charchecker/src/main/resources/doc/rules/LowercaseRule.md[]
This rule belongs to the `Letter` category

UpercaseRule::
include::../../charchecker/src/main/resources/doc/rules/UpercaseRule.md[]
This rule belongs to the `Letter` category

NumberRule::
include::../../charchecker/src/main/resources/doc/rules/NumberRule.md[]
This rule belongs to the `Number` category

=== Project examples

These example projects provide some content for the linters.

==== example-project-txt

git-link:example-project-txt/[example-project-txt (GitHub)] is a simple maven project (`pom` packaging) containing a single text file in the `src` folder.
This `file.txt` contains on purpose some mistakes, that should be marked as error by the <<txtlinter>> linter.

==== example-project-chars

git-link:example-project-txt/[example-project-txt (GitHub)] is a simple maven project (`pom` packaging) containing some text files that should be analyzed by the <<charchecker>>.

=== How to run the linters?

The example projects are tested by the linters.
Different approaches that can be used.
The examples described below execute the `charchecker` linter on the text file contained in the `example-project-txt` project.

==== Specific maven plugins
For the two linters, two specific maven plugin have been created: git-link:txtlinter-maven-plugin/[txtlinter-maven-plugin (GitHub)].

They can be used directly as any other maven plugin:

[source,xml]
----
include::../../example-project-txt/pom.xml[tags="config-maven-plugin", indent="0"]
----

Possible configuration parameters for the maven plugin:

sourceDirectory:: Directory to scan (default value is `${project.basedir}`).
outputType:: Type of report that should be created, possible values:
**** `html` (default)
**** `xml`
outputFile:: Name of the file, where the report will be created (default value is `${project.build.directory}/report.html`).
srcPathPrefix:: Local or remote path to the source directory, if not set (default) a relative path to the local file will be computed. For the `example-project-txt` project in this repository, the remote path to view the files on GitHub is: `https://github.com/jmini/jxlint-experiments/tree/master/example-project-txt/src`.
enableOnlyRules:: Only check for these rules. Ignored if not set (default).
disableRules:: Disable the list of rules. Ignored if not set (default).
enableRules:: Enable the list of rules. Ignored if not set (default).
enableCategories:: Run all rules of certain categories. Ignored if not set (default).
noWarnings:: Only check for errors; ignore warnings. Possible values:
**** `false` (default)
**** `true`
allWarnings:: Check all warnings, including those off by default. Possible values:
**** `false` (default)
**** `true`
waringsAreErrors:: Treat all warnings as errors. Possible values:
**** `false` (default)
**** `true`

==== exec-maven-plugin

The `org.codehaus.mojo:exec-maven-plugin` maven plugin is a generic plugin to run java programs during the build.
This plugin will take care of the classpath (the maven coordinates of the jar we want to use can be indicated, the plugin will derive the correct classpath, considering all maven dependencies of this artifact).
Here is the corresponding configuration taken from the git-link:example-project-txt/pom.xml[example-project-java/pom.xml] file:

[source,xml]
----
include::../../example-project-txt/pom.xml[tags="config-exec-plugin", indent="0"]
----

==== cmd or sh script

It is not likely that the command line tool will be used with the `exec-maven-plugin` (if you are in a maven build, you should use the maven plugin).
Command line tools are often delivered with all their dependencies in a zip file.

Such a zip file is build for the <<txtlinter>>: 
After the build, in the folder: `/txtlinter-cli/target/`, you will find a zip file (`txtlinter-cli-<version>-bin.zip`) containing all the dependencies and two basic scripts `txtlinter.cmd` and `txtlinter.sh` to call the main class with the appropriate classpath.

Discover all available options with:

[source,plain]
----
txtlinter --help
----


=== Output examples

Have a look at the link:example-report.html[html] or link:example-report.xml[xml] version of the report created by the `charchecker` linter after analysis of the files in the `example-project-txt` project.


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

